config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :v1, defaults: { format: :json }  do
    resources :users, only: [:create]
  end
  
  namespace :admin do
    resources :users, except: [:put, :update, :show, :destroy]
  end

  root to: "admin/users#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :model, presence: true
  validates :imei, presence: true
  validates :anual_price, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders, dependent: :destroy
    accepts_nested_attributes_for :orders

    validates :name, presence: true
    validates :cpf, presence: true
    validates :cpf, uniqueness: true


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.eager_load(:orders)
  end

  def new
    @user = User.new
    @order = @user.orders.build
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/v1/users_controller.rb
class V1::UsersController < ApplicationController
  def create
    response = UserService.new(user: user_params).perform
    if response[:valid]
      render json: { user: response[:user], message: "Cliente registrado com sucesso." }.to_json, status: :created
    else
      render json: { errors: response[:error], message: "Houve um erro ao tentar salvar os dados, verifique e tente novamente." }.to_json, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :cpf, :email, orders_attributes: [ :model, :imei, :anual_price, :payment_number_of_quotas ])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/v1/users_helper.rb
module V1::UsersHelper
end

app/views/admin/users/_form.slim
= simple_form_for(user, as: :user, url: v1_users_path ) do |f|
    - unless f.error_notification.blank?
        .alert.alert-danger role="alert"
            = f.error_notification
    h4
        | Cliente
    hr.mt-1
    = f.input :name, required: true
    = f.input :cpf, required: true
    = f.input :email
    
    h4.mt-5
        | Assinatura
    hr.mt-1
    = f.simple_fields_for :orders do |of|
        = of.input :model, required: true
        = of.input :imei, required: true
        = of.input :anual_price, required: true
        = of.input :payment_number_of_quotas

    = f.submit 'Criar Usuário', id: 'user_submit', class: "btn btn-primary mt-5 mb-5"

/! Modals
/! Modal: modalCookie
#modalCookie.modal.fade.top aria-hidden="true" aria-labelledby="myModalLabel" data-backdrop="true" role="dialog" tabindex="-1" 
  .modal-dialog.modal-frame.modal-top.modal-notify.modal-info role="document" 
    /! Content
    .modal-content
      /! Body
      .modal-body
        .row.d-flex.justify-content-center.align-items-center
          p#modalCookieBodyText.pt-3.pr-2 
          a.btn.btn-outline-primary.waves-effect data-dismiss="modal" type="button"  Ok
    /! /.Content
/! Modal: modalCookie

app/views/admin/users/index.slim
h2.mt-5  
    | Listando Clientes
- if @users.blank?
    h4.mt-5
        .alert.alert-light role="alert"
            | Não há usuários para exibir
            p.mt-3
                = link_to "Adicione um agora", new_admin_user_path, class: "btn btn-primary"
- else
    p.mt-5
        table.table
            thead
                tr
                    th scope="col"
                        | ID
                    th 
                        | Nome
                    th 
                        | CPF
                    th
                        | Email
                    th 
                        | Modelo
                    th 
                        | IMEI
                    th
                        | Preço Anual
                    th
                        | Qtd. Parcelas
            tbody
                - @users.each do |user|
                    tr
                        th scope="row"
                            = user.id
                        td 
                            = user.name
                        td 
                            = user.cpf
                        td 
                            = user.email
                        td 
                            = user.orders.first.model
                        td 
                            = user.orders.first.imei
                        td 
                            = user.orders.first.anual_price
                        td 
                            = user.orders.first.payment_number_of_quotas

app/views/admin/users/new.slim
h2.mt-5
  | Criar Novo Cliente

.row.mt-5
  .col.col-md-6
    = render "form", user: @user

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Prcc
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/partials/header"
    
    .container
      = yield

app/views/layouts/partials/_header.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.static-top
    .container
      a.navbar-brand href="/"  Clientes
      button.navbar-toggler aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      #navbarResponsive.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          li.nav-item
            a.nav-link href="/" 
              | Listar
              span
          li.nav-item
            = link_to "Novo", new_admin_user_path, class: "nav-link"